###
GET http://localhost:8080/
Accept: application/json

###
GET http://localhost:8080/profile
Accept: application/json



###OBTENER TODOS LOS REGISTROS
GET http://localhost:8080/languages
Accept: application/json

###OBTENER UN REGISTRO
GET http://localhost:8080/languages/1
Accept: application/json

###CREAR UN REGISTRO
POST http://localhost:8080/languages
Content-Type: application/json

{
    "name": "Prueba",
    "last_update": "2006-02-15"
}

###ELIMINAR UN REGISTRO
DELETE  http://localhost:8080/languages/9
Accept: application/json

###MODIFICAR UN REGISTRO
PUT  http://localhost:8080/languages/9
Content-Type: application/json

{
    "name": "Prueba_Modificada",
    "last_update": "2006-08-15"
}

